### PR TITLE
Dusan improvements

### PR DESCRIPTION
**Pull request by lalvarezguillen**
Imported changes that Dusan made to our copy of the codebase, removing styling improvements to keep the diff as small as possible.

### CODE REVIEW

**Comment by lalvarezguillen** [comment]
@normoes this ports the functional improvements we made.

I've removed the styling improvements we made, to keep the diff small, because I intend to propose these changes to the original repo. We can re-introduce them later.

Could you take a look please?

**Comment by normoes** [comment]
@lalvarezguillen 

Looks good to me. +1 for introducing `logging` :)

Thanks for migrating this!

**Comment by normoes** [comment]
@lalvarezguillen 

Is `create_stat_info_reques()t` used anywhere?

It is defined in `bucket.py`.

**Comment by lalvarezguillen** [comment]
> @lalvarezguillen
> 
> Is `create_stat_info_reques()t` used anywhere?
> 
> It is defined in `bucket.py`.

Dusan defined it. It's a levin method that wasn't implemented before, and the network crawler required it

**Pull request merged**
